[menu]
    [[menu.main]]
        name = "关于"
        pageRef = "about"
        weight = 10
        [menu.main.params]
            icon = "user"
            newTab = false
    [[menu.main]]
        name = "Tags"
        pageRef = "tags"
        weight = 20
        [menu.main.params]
            icon = "tag"
            newTab = false
