[build]
publish = "public"
command = """\
  git config --global core.quotepath false && \
  hugo build --gc --minify --baseURL "${URL}"
  """

[build.environment]
GO_VERSION = "1.22.0"
HUGO_VERSION = "0.167.0"
NODE_VERSION = "24.21.0"
TZ = "Asia/Shanghai"
